[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = ["cd backend && npm run build --if-present"]

[build]
cmd = "cd backend && npm ci"

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production" 