name: Deploy ScoopSocials

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-frontend:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
      env:
        NEXT_PUBLIC_API_URL: https://scoopsocials-clean-production.up.railway.app
    
    - name: Deploy to Vercel
      run: |
        npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --force
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  health-check:
    name: Health Check After Deployment
    runs-on: ubuntu-latest
    needs: [deploy-frontend]
    
    steps:
    - name: Check Backend Health
      run: |
        curl -f https://scoopsocials-clean-production.up.railway.app/health || echo "Backend health check failed but continuing..."
    
    - name: Notify Success
      if: success()
      run: |
        echo "🎉 ScoopSocials frontend deployed successfully!"
        echo "Frontend: GitHub Pages"
        echo "Backend: https://scoopsocials-clean-production.up.railway.app" 